version: '3.5'

services:
    
    backend:
        build: ./backend
        restart: unless-stopped
        ports:
            - 8000:8000
        volumes:
            - ./backend/logs.txt:/backend_app/logs.txt
        environment:
            - REDIS=redis
    
    frontend:
        build: ./frontend
        ports:
            - 5000:5000

    redis:
        image: redis
