version: '3.5'

services:
    
    backend:
        build: ./backend
        restart: unless-stopped
        ports:
            - 8000:8000
        volumes:
            - ./backend/logs.txt:/backend_app/logs.txt
        environment:
            - REDIS=redis
            - DB_USERNAME=db_user
            - DB_PASSWORD=db_password
            - DB_HOST=db
        depends_on:
            - db
    
    frontend:
        build: ./frontend
        ports:
            - 5000:5000

    redis:
        image: redis

    db:
        image: postgres
        environment:
            - POSTGRES_USER=db_user
            - POSTGRES_PASSWORD=db_password

    nginx:
        image: nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
